version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nullnode
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password