version: "3.7"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm run migrate:dev && npm run start:dev"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nullnode
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U development -d nullnode" ]
      interval: 5s
      timeout: 3s
      retries: 5
