version: "3.7"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://username:1234567@postgres:5432/nullnode?connect_timeout=300
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    command: sh -c "npx prisma migrate dev && npm run start:dev"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nullnode
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=1234567
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 5
