name: nullnode-api ci

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

env:
  DATABASE_URL: postgres://test:password@localhost:5432/nullnode
  POSTGRES_NAME: postgres

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      - name: Install packages
        run: npm install
      - name: Generate Prisma schema
        run: npx prisma generate
      - name: Start Postgres Docker container
        run: docker-compose -f docker-compose.test.yml up -d
      - name: Wait for Postgres
        run: until docker-compose exec -T $POSTGRES_NAME pg_isready; do sleep 5; done
      - name: Run migrations
        run: npx prisma migrate deploy
      - name: Run tests
        run: npm test
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - name: Stop Docker
        run: docker-compose down
